# .air.toml

# Config file for Air
[build]
  cmd = "go build -o ./tmp/main ./cmd/internals"
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["air.toml"]
  follow_symlink = true
  dir = "."
  log = "air_errors.log"
  # exclude_regex = ["_test\\.go"]

[log]
  color = true
  timestamp = false

[serve]
  grace = 2000
  root = "."
  cmd = "make serve"
  bin = "APP_ENV=dev ./tmp/main"
  port = 8000
  watch_delay = 200
  watch = ["."]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["air.toml"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  follow_symlink = true
  dir = "."
  log = "air_errors.log"
  exclude_regex = ["_test\\.go"]